apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  replicas: 1
  serviceName: prometheus
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: prometheus
          image: prom/prometheus:v2.22.0
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"          
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9090
#          envFrom:
#            - configMapRef:
#                name: postgres-config
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-config-volume
              subPath: prometheus.yml
            - name: prometheus-storage-volume
              mountPath: /prometheus/              
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus
  
        - name: prometheus-storage-volume
          emptyDir: {}              
