---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: ks-listpod
  namespace: default
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ks-listpod-role
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---   
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: ks-listpod-rolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ks-listpod-role
subjects:
- kind: ServiceAccount
  name: ks-listpod
  namespace: default
---  
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kube-pod
  name: kube-pod
spec:
  serviceAccountName: ks-listpod
  containers:
  - image: kanisterio/kanister-kubectl:1.18
    name: kube-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
