---
apiVersion: v1
data:
  name: demo
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cm-one
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
        - name: env
          valueFrom:
            configMapKeyRef:
              name: cm-one
              key: name
